"use client";
import MUIProvider from "@/lib/providers/MUIProvider";
import ReduxProvider from "@/lib/providers/ReduxProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MUIProvider>
      <html lang="en">
        <ReduxProvider>
          <body className={inter.className}>{children}</body>
        </ReduxProvider>
      </html>
    </MUIProvider>
  );
}
